cabal-version:   3.0
name:            copl-solver
version:         0.1.0.0
license:         MIT
license-file:    LICENSE
author:          itoooak
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Common.Syntax,
        Common.Parser,
        Derivation.Nat,
        Derivation.CompareNatCommon,
        Derivation.CompareNat1,
        Derivation.CompareNat2,
        Derivation.CompareNat3,
        Derivation.EvalNatExp
    other-modules:
    build-depends:    parser-combinators, megaparsec, base ^>=4.20.2.0
    hs-source-dirs:   src
    default-language: GHC2024

executable copl-solver
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base ^>=4.20.2.0,
        copl-solver

    hs-source-dirs:   app
    default-language: GHC2024

test-suite copl-solver-test
    import:           warnings
    default-language: GHC2024
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base ^>=4.20.2.0,
        copl-solver
