cabal-version:   3.0
name:            copl-solver
version:         0.1.0.0
license:         MIT
license-file:    LICENSE
author:          itoooak
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Parser,
        DrvFormat,
        DrvSystem.Nat,
        DrvSystem.CompareNat.Base,
        DrvSystem.CompareNat.System1,
        DrvSystem.CompareNat.System2,
        DrvSystem.CompareNat.System3,
        DrvSystem.EvalNatExp,
        DrvSystem.ReduceNatExp,
        DrvSystem.EvalML1,
        DrvSystem.EvalML1Err,
        DrvSystem.EvalML2,
        DrvSystem.EvalML3,
        DrvSystem.NamelessML3,
        DrvSystem.EvalNamelessML3,
        DrvSystem.EvalML4,
        DrvSystem.TypingML4,
        DrvSystem.PolyTypingML4,
        DrvSystem.EvalContML1,
        DrvSystem.EvalContML4,
        DrvSystem.EvalRefML3,
        DrvSystem.While,
        DrvSystem.EvalML5
    other-modules:
    build-depends:    containers, mtl, parser-combinators, megaparsec, base ^>=4.20.2.0
    hs-source-dirs:   src
    default-language: GHC2024

executable copl-solver
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base ^>=4.20.2.0,
        copl-solver

    hs-source-dirs:   app
    default-language: GHC2024

test-suite copl-solver-test
    import:           warnings
    default-language: GHC2024
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base ^>=4.20.2.0,
        copl-solver
