cabal-version:   3.0
name:            copl-solver
version:         0.1.0.0
license:         MIT
license-file:    LICENSE
author:          itoooak
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Common.Parser,
        Derivation.Format,
        Derivation.Nat.Shared,
        Derivation.Nat.System,
        Derivation.CompareNat.Shared,
        Derivation.CompareNat.System1,
        Derivation.CompareNat.System2,
        Derivation.CompareNat.System3,
        Derivation.EvalNatExp,
        Derivation.ReduceNatExp,
        Derivation.EvalML1.Shared,
        Derivation.EvalML1,
        Derivation.EvalML1Err,
        Derivation.EvalML2.Shared,
        Derivation.EvalML2,
        Derivation.EvalML3.Shared,
        Derivation.EvalML3,
        Derivation.NamelessML3,
        Derivation.EvalNamelessML3,
        Derivation.EvalML4.Shared,
        Derivation.EvalML4,
        Derivation.TypingML4
    other-modules:
    build-depends:    mtl, parser-combinators, megaparsec, base ^>=4.20.2.0
    hs-source-dirs:   src
    default-language: GHC2024

executable copl-solver
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base ^>=4.20.2.0,
        copl-solver

    hs-source-dirs:   app
    default-language: GHC2024

test-suite copl-solver-test
    import:           warnings
    default-language: GHC2024
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base ^>=4.20.2.0,
        copl-solver
